services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: bioclean
      POSTGRES_PASSWORD: bioclean
      POSTGRES_DB: bioclean
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
