"""add tax_amount to sales

Revision ID: 09a35017bb1d
Revises: 25c5501ba204
Create Date: 2026-09-23 20:32:05.576949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a35017bb1d'
down_revision: Union[str, None] = '25c5501ba204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand - see 25c5501ba204's identical fix.
    # Existing sales predate the tax_rate concept entirely, so 0 is the
    # only correct backfill (they weren't taxed).
    op.add_column('sales', sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'tax_amount')
    # ### end Alembic commands ###
