"""add barcode reorder wholesale supplier active and per-warehouse stock

Revision ID: 15808ae4ee21
Revises: 576838a2d5e5
Create Date: 2026-09-22 23:13:47.005809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15808ae4ee21'
down_revision: Union[str, None] = '576838a2d5e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_table('item_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'warehouse_id', name='uq_item_warehouse')
    )
    op.create_index(op.f('ix_item_stock_id'), 'item_stock', ['id'], unique=False)
    op.add_column('items', sa.Column('barcode', sa.String(), nullable=True))
    op.add_column('items', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('items', sa.Column('wholesale_price', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('items', sa.Column('reorder_level', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('items', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('items', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_items_barcode'), 'items', ['barcode'], unique=True)
    op.create_foreign_key(None, 'items', 'suppliers', ['supplier_id'], ['id'])

    # Seed the one warehouse that exists today, then carry every item's
    # existing stock_qty into it before the column is dropped - a schema
    # change should never silently erase real stock data.
    op.execute("INSERT INTO warehouses (name, is_default) VALUES ('Main Store', true)")
    op.execute(
        """
        INSERT INTO item_stock (item_id, warehouse_id, qty)
        SELECT items.id, warehouses.id, items.stock_qty
        FROM items, warehouses
        WHERE warehouses.name = 'Main Store'
        """
    )
    op.drop_column('items', 'stock_qty')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('stock_qty', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False, server_default='0'))
    op.execute(
        """
        UPDATE items SET stock_qty = COALESCE(
            (SELECT SUM(qty) FROM item_stock WHERE item_stock.item_id = items.id), 0
        )
        """
    )
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_index(op.f('ix_items_barcode'), table_name='items')
    op.drop_column('items', 'supplier_id')
    op.drop_column('items', 'is_active')
    op.drop_column('items', 'reorder_level')
    op.drop_column('items', 'wholesale_price')
    op.drop_column('items', 'image_url')
    op.drop_column('items', 'barcode')
    op.drop_index(op.f('ix_item_stock_id'), table_name='item_stock')
    op.drop_table('item_stock')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
