"""add purchase order payment status

Revision ID: 1fd82b146f37
Revises: 82452b1ca276
Create Date: 2026-09-24 19:09:25.782476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd82b146f37'
down_revision: Union[str, None] = '82452b1ca276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('payment_status', sa.String(), nullable=False, server_default='unpaid'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'payment_status')
    # ### end Alembic commands ###
