"""merge item_code into barcode remove is_active add unit_cost

Revision ID: 210a06f557f6
Revises: dbc7c97b976e
Create Date: 2026-09-23 01:26:31.151123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210a06f557f6'
down_revision: Union[str, None] = 'dbc7c97b976e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'barcode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_items_item_code', table_name='items')
    op.drop_column('items', 'item_code')
    op.drop_column('items', 'is_active')
    op.add_column('stock_movements', sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###

    # Confirmed decision: unit of measure defaults to PCS, not the old Nos.
    op.execute("UPDATE items SET uom = 'PCS' WHERE uom = 'Nos'")
    # Confirmed decision: every item gets a real reorder level rather than
    # 0 (which meant "never reorder") - 10 matches the new model default.
    op.execute("UPDATE items SET reorder_level = 10 WHERE reorder_level = 0")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_movements', 'unit_cost')
    op.add_column('items', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    # item_code was merged into barcode and can't be un-derived - this
    # downgrade path is best-effort only, backfilling with barcode's value
    # so the column at least isn't left null, not a true reversal.
    op.add_column('items', sa.Column('item_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.execute("UPDATE items SET item_code = barcode")
    op.alter_column('items', 'item_code', nullable=False)
    op.create_index('ix_items_item_code', 'items', ['item_code'], unique=True)
    op.alter_column('items', 'barcode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
