"""add tax rate to app settings

Revision ID: 25c5501ba204
Revises: 559bacc4bf30
Create Date: 2026-09-23 20:28:50.636387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c5501ba204'
down_revision: Union[str, None] = '559bacc4bf30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand: autogenerate left this NOT NULL with no
    # default, which fails outright against the existing app_settings row
    # (id=1) already sitting in every real database. Matches the model's
    # Python-side default=0 for any row inserted after this migration.
    op.add_column('app_settings', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'tax_rate')
    # ### end Alembic commands ###
