"""add unit_cost to invoice_lines and sale_lines

Revision ID: 37f2e6260561
Revises: e4299fb9e896
Create Date: 2026-09-24 00:32:14.518145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f2e6260561'
down_revision: Union[str, None] = 'e4299fb9e896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand - both tables are empty today, but this
    # matches the model's Python-side default=0 and avoids a NOT NULL
    # failure if that ever isn't true by the time this runs.
    op.add_column('invoice_lines', sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('sale_lines', sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_lines', 'unit_cost')
    op.drop_column('invoice_lines', 'unit_cost')
    # ### end Alembic commands ###
