"""add pdf_data cache to invoices

Revision ID: 630b6587df15
Revises: 09a35017bb1d
Create Date: 2026-09-23 22:50:40.796452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '630b6587df15'
down_revision: Union[str, None] = '09a35017bb1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('pdf_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'pdf_data')
    # ### end Alembic commands ###
