"""add lbp_rounding to app_settings

Revision ID: 7e952d7ff95e
Revises: dc578bd98c5b
Create Date: 2026-09-24 18:37:34.522277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e952d7ff95e'
down_revision: Union[str, None] = 'dc578bd98c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand - app_settings already has its singleton
    # row, matching the model's Python-side default=1000.
    op.add_column('app_settings', sa.Column('lbp_rounding', sa.Numeric(precision=10, scale=0), nullable=False, server_default='1000'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'lbp_rounding')
    # ### end Alembic commands ###
