"""drop shelf_location and supplier_id from items

Revision ID: 7ea7bdbbca71
Revises: 630b6587df15
Create Date: 2026-09-23 23:48:17.459896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea7bdbbca71'
down_revision: Union[str, None] = '630b6587df15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_supplier_id_fkey', 'items', type_='foreignkey')
    op.drop_column('items', 'shelf_location')
    op.drop_column('items', 'supplier_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('shelf_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('items_supplier_id_fkey', 'items', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###
