"""allow item and supplier fk to be nulled on delete

Revision ID: 81edba9e23e2
Revises: 1fd82b146f37
Create Date: 2026-09-24 19:34:24.758364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81edba9e23e2'
down_revision: Union[str, None] = '1fd82b146f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice_lines', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('purchase_order_lines', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('purchase_orders', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quotation_lines', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('return_lines', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sale_lines', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_lines', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('return_lines', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quotation_lines', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('purchase_orders', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('purchase_order_lines', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invoice_lines', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
