"""add returns and returned_total

Revision ID: 82452b1ca276
Revises: 7e952d7ff95e
Create Date: 2026-09-24 18:47:28.949713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82452b1ca276'
down_revision: Union[str, None] = '7e952d7ff95e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('refund_method', sa.String(), nullable=False),
    sa.Column('total_refund', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_returns_created_at'), 'returns', ['created_at'], unique=False)
    op.create_index(op.f('ix_returns_id'), 'returns', ['id'], unique=False)
    op.create_index(op.f('ix_returns_sale_id'), 'returns', ['sale_id'], unique=False)
    op.create_table('return_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('sale_line_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_refund', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], ),
    sa.ForeignKeyConstraint(['sale_line_id'], ['sale_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_lines_id'), 'return_lines', ['id'], unique=False)
    op.create_index(op.f('ix_return_lines_item_id'), 'return_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_return_lines_return_id'), 'return_lines', ['return_id'], unique=False)
    op.create_index(op.f('ix_return_lines_sale_line_id'), 'return_lines', ['sale_line_id'], unique=False)
    op.add_column('sales', sa.Column('returned_total', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'returned_total')
    op.drop_index(op.f('ix_return_lines_sale_line_id'), table_name='return_lines')
    op.drop_index(op.f('ix_return_lines_return_id'), table_name='return_lines')
    op.drop_index(op.f('ix_return_lines_item_id'), table_name='return_lines')
    op.drop_index(op.f('ix_return_lines_id'), table_name='return_lines')
    op.drop_table('return_lines')
    op.drop_index(op.f('ix_returns_sale_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_created_at'), table_name='returns')
    op.drop_table('returns')
    # ### end Alembic commands ###
