"""add idempotency_key to sales

Revision ID: 8f31c3297b89
Revises: 37f2e6260561
Create Date: 2026-09-24 00:48:41.936708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f31c3297b89'
down_revision: Union[str, None] = '37f2e6260561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_sales_idempotency_key'), 'sales', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_idempotency_key'), table_name='sales')
    op.drop_column('sales', 'idempotency_key')
    # ### end Alembic commands ###
