"""add pdf_data cache to purchase_orders and quotations

Revision ID: d4518adf9ecb
Revises: 7ea7bdbbca71
Create Date: 2026-09-24 00:02:08.371957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4518adf9ecb'
down_revision: Union[str, None] = '7ea7bdbbca71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('pdf_data', sa.LargeBinary(), nullable=True))
    op.add_column('quotations', sa.Column('pdf_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'pdf_data')
    op.drop_column('purchase_orders', 'pdf_data')
    # ### end Alembic commands ###
