"""add qty_before user reference to stock movements

Revision ID: dbc7c97b976e
Revises: e2abebbdbf33
Create Date: 2026-09-23 00:49:30.360593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc7c97b976e'
down_revision: Union[str, None] = 'e2abebbdbf33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_movements', sa.Column('qty_before', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('stock_movements', sa.Column('user', sa.String(), nullable=False, server_default='admin'))
    op.add_column('stock_movements', sa.Column('reference', sa.String(), nullable=True))
    op.create_index(op.f('ix_stock_movements_created_at'), 'stock_movements', ['created_at'], unique=False)

    # Existing rows never had qty_before - it's fully derivable from data
    # we already have (qty_after - delta), so backfill it exactly rather
    # than guessing with a flat default.
    op.execute("UPDATE stock_movements SET qty_before = qty_after - delta WHERE qty_before IS NULL")
    op.alter_column('stock_movements', 'qty_before', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_created_at'), table_name='stock_movements')
    op.drop_column('stock_movements', 'reference')
    op.drop_column('stock_movements', 'user')
    op.drop_column('stock_movements', 'qty_before')
    # ### end Alembic commands ###
