"""add printer settings

Revision ID: dc578bd98c5b
Revises: dda98c2c3583
Create Date: 2026-09-24 18:28:08.176892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc578bd98c5b'
down_revision: Union[str, None] = 'dda98c2c3583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand - app_settings already has its one
    # singleton row (id=1) in every real install, so this NOT NULL add
    # needs a backfill value, same as the model's Python-side default="none".
    op.add_column('app_settings', sa.Column('printer_connection_type', sa.String(), nullable=False, server_default='none'))
    op.add_column('app_settings', sa.Column('printer_target', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'printer_target')
    op.drop_column('app_settings', 'printer_connection_type')
    # ### end Alembic commands ###
