"""add exchange_rate_history and snapshot exchange_rate on sales and invoices

Revision ID: dda98c2c3583
Revises: 8f31c3297b89
Create Date: 2026-09-24 01:00:37.272130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda98c2c3583'
down_revision: Union[str, None] = '8f31c3297b89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rate_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usd_to_lbp_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_rate_history_effective_at'), 'exchange_rate_history', ['effective_at'], unique=False)
    op.create_index(op.f('ix_exchange_rate_history_id'), 'exchange_rate_history', ['id'], unique=False)
    # server_default added by hand - both tables are empty today, but this
    # matches the models' Python-side default=0 and avoids a NOT NULL
    # failure if that ever isn't true by the time this runs.
    op.add_column('invoices', sa.Column('exchange_rate', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('sales', sa.Column('exchange_rate', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'exchange_rate')
    op.drop_column('invoices', 'exchange_rate')
    op.drop_index(op.f('ix_exchange_rate_history_id'), table_name='exchange_rate_history')
    op.drop_index(op.f('ix_exchange_rate_history_effective_at'), table_name='exchange_rate_history')
    op.drop_table('exchange_rate_history')
    # ### end Alembic commands ###
