"""add pdf_data cache to sales

Revision ID: e4299fb9e896
Revises: d4518adf9ecb
Create Date: 2026-09-24 00:18:56.081624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4299fb9e896'
down_revision: Union[str, None] = 'd4518adf9ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('pdf_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'pdf_data')
    # ### end Alembic commands ###
