"""snapshot customer and supplier names on documents

Revision ID: ee244108e013
Revises: 81edba9e23e2
Create Date: 2026-09-24 19:37:58.454448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee244108e013'
down_revision: Union[str, None] = '81edba9e23e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('customer_name', sa.String(), nullable=True))
    op.add_column('purchase_orders', sa.Column('supplier_name', sa.String(), nullable=True))
    op.add_column('quotations', sa.Column('customer_name', sa.String(), nullable=True))
    # ### end Alembic commands ###

    # Backfill from the live relationship for anything created before this
    # column existed - without this, every pre-existing invoice/PO/
    # quotation would show a blank customer/supplier the moment its FK is
    # ever nulled out (see customers/router.py, suppliers/router.py).
    op.execute("UPDATE invoices SET customer_name = customers.name FROM customers WHERE invoices.customer_id = customers.id")
    op.execute("UPDATE quotations SET customer_name = customers.name FROM customers WHERE quotations.customer_id = customers.id")
    op.execute("UPDATE purchase_orders SET supplier_name = suppliers.name FROM suppliers WHERE purchase_orders.supplier_id = suppliers.id")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'customer_name')
    op.drop_column('purchase_orders', 'supplier_name')
    op.drop_column('invoices', 'customer_name')
    # ### end Alembic commands ###
